# Generated by Django 3.2.9 on 2022-01-21 20:48

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False, unique=True)),
                ('img', models.ImageField(upload_to='news/images/cover/')),
                ('category', models.CharField(blank=True, choices=[('News', 'News'), ('Gaming News', 'Gaming News')], max_length=250, null=True)),
                ('headline', models.CharField(max_length=500)),
                ('dec', models.TextField(blank=True, null=True)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('button_text1', models.CharField(blank=True, max_length=255, null=True)),
                ('link_url1', models.URLField(blank=True, max_length=1000, null=True)),
                ('offer_Button', models.CharField(blank=True, max_length=255, null=True)),
                ('offer', models.CharField(blank=True, max_length=250, null=True)),
                ('activate', models.BooleanField(default=True)),
                ('create_on', models.DateField(auto_now_add=True)),
                ('text2', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
                'db_table': 'news',
            },
        ),
    ]
